[package]
name = "file-metadata-mditem-macros"
version = "0.0.1"
authors = ["Domenico Shura <shura1991@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "0.15.35"
quote = "0.6.12"
